version: '3.1'

services:

  db:
    container_name: mysql_docker
    hostname: mysql_docker
    image: mysql
    restart: always
    
    command: 
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
    
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - ~/Área de Trabalho/MySQL_Docker:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080